name: Filter Blacklist
on:
  push:
    paths:
      - 'pihole_blacklist.txt'
      - 'filter_blacklist.py'
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'  # 12 malam WIB
permissions:
  contents: write
jobs:
  run-filter:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install requests
      run: pip install requests
    
    - name: Jalankan filter
      run: python3 filter_blacklist.py
    
    - name: Commit dan push hasil
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add pihole_blacklist.txt
        git commit -m "Update filtered pihole_blacklist.txt" || echo "Tidak ada perubahan"
        git push
